export { default as App } from './App';
export { default as ProductCard } from './ProductCard';
export { default as HomePage } from './HomePage';
export { default as Header } from './Header';
export { default as ContemporaryPage } from './ContemporaryPage';
export { default as CubismPage } from './CubismPage';
export { default as ImpressionismPage } from './ImpressionismPage';
export { default as PopartPage } from './PopartPage';
export { default as PostImpressionismPage } from './PostImpressionismPage';
export { default as Register } from './Register';
// export { default as Login } from './Login';
